<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mahasiswa_model extends CI_Model
{

    public $table = 'calon_mahasiswa';
    public $id = 'id_daftar';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_daftar,nama,email,no_hp,asal_sekolah,ttl,alamat,nama_prodi,jk,thn_lulus');
        $this->datatables->from('calon_mahasiswa');
        //add this line for join
        $this->datatables->join('prodi', 'calon_mahasiswa.prodi_pilihan = prodi.id_prodi');
        $this->datatables->add_column('action', anchor('#','Update',array('class'=>"btn btn-primary"))." | ".anchor(site_url('admin/mahasiswa/delete/$1'),'Delete','class="btn btn-danger" onclick="return confirm(\'Yakin ingin menghapus data ini ?\')"'),'id_daftar');
        return $this->datatables->generate();
    }

    function prodi_json(){
        $this->datatables->select('id_prodi, nama_prodi, jurusan');
        $this->datatables->from('prodi');
        $this->datatables->add_column('action', anchor('#','Update',array('class'=>"btn btn-primary",'data-id_prodi'=>'$1','data-nama_prodi'=>'$2','data-jurusan'=>'$3','data-toggle'=>'modal','data-target'=>'#ubah-data','data-backdrop'=>'false'))." | ".anchor(site_url('admin/prodi/delete/$1'),'Delete','class="btn btn-danger" onclick="return confirm(\'Yakin ingin menghapus data ini ?\')"'),'id_prodi','nama_prodi','jurusan');
        return $this->datatables->generate();
    }
    function kategori_json(){
        $this->datatables->select('id_kategori, nama_kategori');
        $this->datatables->from('kategori');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    // get email
    function get_by_email($email){
        $this->db->where('email', $email);
        return $this->db->get($this->table);
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_daftar', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('asal_sekolah', $q);
	$this->db->or_like('ttl', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('prodi_pilihan', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('thn_lulus', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_daftar', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('asal_sekolah', $q);
	$this->db->or_like('ttl', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('prodi_pilihan', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('thn_lulus', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
    function insert_prodi($data)
    {
        $this->db->insert('prodi', $data);
    }
    function insert_kategori($data)
    {
        $this->db->insert('kategori', $data);
    }
    function update_prodi($id, $data)
    {
        $this->db->where('id_prodi', $id);
        $this->db->update('prodi', $data);
    }
    function update_kategori($id, $data)
    {
        $this->db->where('id_kategori', $id);
        $this->db->update('kategori', $data);
    }


    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function delete_prodi($id)
    {
        $this->db->where('id_prodi', $id);
        $this->db->delete('prodi');
    }
    function delete_kategori($id)
    {
        $this->db->where('id_kategori', $id);
        $this->db->delete('kategori');
    }

}

/* End of file Mahasiswa_model.php */
/* Location: ./application/models/Mahasiswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-21 09:14:39 */
/* http://harviacode.com */