<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Soal_model extends CI_Model
{

    public $table = 'soal';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,id_prodi,id_fakultas,id_kategori,soal,opsi_a,opsi_b,opsi_c,opsi_d,opsi_e,jawaban,tgl_input');
        $this->datatables->from('soal');
        //add this line for join
        //$this->datatables->join('table2', 'soal.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/soal/update/$1'),'Update',array('class'=>"btn btn-primary"))." | ".anchor(site_url('admin/soal/delete/$1'),'Delete','class="btn btn-danger" onclick="return confirm(\'Yakin Ingin menghapus data ini !\')"') , 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_prodi', $q);
	$this->db->or_like('id_fakultas', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('soal', $q);
	$this->db->or_like('opsi_a', $q);
	$this->db->or_like('opsi_b', $q);
	$this->db->or_like('opsi_c', $q);
	$this->db->or_like('opsi_d', $q);
	$this->db->or_like('opsi_e', $q);
	$this->db->or_like('jawaban', $q);
	$this->db->or_like('tgl_input', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_prodi', $q);
	$this->db->or_like('id_fakultas', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('soal', $q);
	$this->db->or_like('opsi_a', $q);
	$this->db->or_like('opsi_b', $q);
	$this->db->or_like('opsi_c', $q);
	$this->db->or_like('opsi_d', $q);
	$this->db->or_like('opsi_e', $q);
	$this->db->or_like('jawaban', $q);
	$this->db->or_like('tgl_input', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Soal_model.php */
/* Location: ./application/models/Soal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-21 16:27:23 */
/* http://harviacode.com */